vehicle:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Effort Controllers ---------------------------------------
  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint4
    pid: {p: 100.0, i: 0.01, d: 10.0}
