<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="vehicle" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.3" /> <!-- Square dimensions (widthxwidth) of vehicle body -->
  <xacro:property name="length" value="0.5" /> <!-- Link 1 -->
  <xacro:property name="height" value="0.2" /> <!-- Link 2 -->
  <xacro:property name="wheel_d" value="0.1" /> <!-- Wheel diameter -->
  <xacro:property name="wheel_t" value="0.02" /> <!-- Wheel thickness -->
  <xacro:property name="gap" value="0.02" /> <!-- Wheel gap -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find vehicle_description)/urdf/vehicle.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find vehicle_description)/urdf/materials.xacro" />

  <!-- Body Link  -->
  <link name="body">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
				<box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
				<box size="${length} ${width} ${height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
			ixx="${mass / 12.0 * (width*width + height*height)}" ixy="0.0" ixz="0.0"
			iyy="${mass / 12.0 * (length*length + height*height)}" iyz="0.0"
			izz="${mass / 12.0 * (width*width + width*width)}"/>
		</inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="body"/>
    <child link="wheel_lf"/>
    <origin xyz="${length/2-wheel_d/2} ${width/2} ${-height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <joint name="joint2" type="continuous">
    <parent link="body"/>
    <child link="wheel_rf"/>
    <origin xyz="${length/2-wheel_d/2} ${-width/2} ${-height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <joint name="joint3" type="continuous">
    <parent link="body"/>
    <child link="wheel_lb"/>
    <origin xyz="${-length/2+wheel_d/2} ${width/2} ${-height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <joint name="joint4" type="continuous">
    <parent link="body"/>
    <child link="wheel_rb"/>
    <origin xyz="${-length/2+wheel_d/2} ${-width/2} ${-height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <joint name="joint5" type="fixed">
    <parent link="body"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>
	
	<!-- IMU Link-->
  <link name="imu_link">
    <collision>
      <origin xyz="0 0 ${camera_link/2}" rpy="0 0 0"/>
      <geometry>
				<box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${camera_link/2}" rpy="0 0 0"/>
      <geometry>
				<box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 ${camera_link/2}" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <!-- Wheel Link -->
  <link name="wheel_lf">
    <collision>
      <origin xyz="0 ${wheel_t/2+gap} 0" rpy="${PI/2} 0 0"/>
      <geometry>
				<cylinder radius="${wheel_d/2}" length="${wheel_t}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${wheel_t/2+gap} 0" rpy="${PI/2} 0 0"/>
      <geometry>
				<cylinder radius="${wheel_d/2}" length="${wheel_t}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 ${wheel_t/2+gap} 0" rpy="${PI/2} 0 0"/>
      <mass value="${mass/10}"/>
      <inertia
			ixx="${mass / 12.0 * (wheel_t*wheel_t*2)}" ixy="0.0" ixz="0.0"
			iyy="${mass / 12.0 * (wheel_t*wheel_t*2)}" iyz="0.0"
			izz="${mass / 12.0 * (wheel_d*wheel_d+wheel_t*wheel_t)}"/>
			</inertial>
  </link>

  <!-- Wheel Link -->
  <link name="wheel_rf">
    <collision>
      <origin xyz="0 ${-wheel_t/2-gap} 0" rpy="${PI/2} 0 0"/>
      <geometry>
				<cylinder radius="${wheel_d/2}" length="${wheel_t}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${-wheel_t/2-gap} 0" rpy="${PI/2} 0 0"/>
      <geometry>
				<cylinder radius="${wheel_d/2}" length="${wheel_t}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 ${-wheel_t/2-gap} 0" rpy="${PI/2} 0 0"/>
      <mass value="${mass/10}"/>
      <inertia
			ixx="${mass / 12.0 * (wheel_t*wheel_t*2)}" ixy="0.0" ixz="0.0"
			iyy="${mass / 12.0 * (wheel_t*wheel_t*2)}" iyz="0.0"
			izz="${mass / 12.0 * (wheel_d*wheel_d+wheel_t*wheel_t)}"/>
			</inertial>
  </link>

  <!-- Wheel Link -->
  <link name="wheel_lb">
    <collision>
      <origin xyz="0 ${wheel_t/2+gap} 0" rpy="${PI/2} 0 0"/>
      <geometry>
				<cylinder radius="${wheel_d/2}" length="${wheel_t}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${wheel_t/2+gap} 0" rpy="${PI/2} 0 0"/>
      <geometry>
				<cylinder radius="${wheel_d/2}" length="${wheel_t}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 ${wheel_t/2+gap} 0" rpy="${PI/2} 0 0"/>
      <mass value="${mass/10}"/>
      <inertia
			ixx="${mass / 12.0 * (wheel_t*wheel_t*2)}" ixy="0.0" ixz="0.0"
			iyy="${mass / 12.0 * (wheel_t*wheel_t*2)}" iyz="0.0"
			izz="${mass / 12.0 * (wheel_d*wheel_d+wheel_t*wheel_t)}"/>
			</inertial>
  </link>

  <!-- Wheel Link -->
  <link name="wheel_rb">
    <collision>
      <origin xyz="0 ${-wheel_t/2-gap} 0" rpy="${PI/2} 0 0"/>
      <geometry>
				<cylinder radius="${wheel_d/2}" length="${wheel_t}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${-wheel_t/2-gap} 0" rpy="${PI/2} 0 0"/>
      <geometry>
				<cylinder radius="${wheel_d/2}" length="${wheel_t}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 ${-wheel_t/2-gap} 0" rpy="${PI/2} 0 0"/>
      <mass value="${mass/10}"/>
      <inertia
			ixx="${mass / 12.0 * (wheel_t*wheel_t*2)}" ixy="0.0" ixz="0.0"
			iyy="${mass / 12.0 * (wheel_t*wheel_t*2)}" iyz="0.0"
			izz="${mass / 12.0 * (wheel_d*wheel_d+wheel_t*wheel_t)}"/>
			</inertial>
  </link>

	<!-- Camera Joint -->
  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${length/2} 0 0" rpy="0 0 0"/>
    <parent link="body"/>
    <child link="camera_link"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="${camera_link/2} 0 0" rpy="0 0 0"/>
      <geometry>
				<box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${camera_link/2} 0 0" rpy="0 0 0"/>
      <geometry>
				<box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="${camera_link/2} 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
      so that ros and opencv can operate on the camera frame correctly -->
  <joint name="camera_optical_joint" type="fixed">
    <!-- these values have to be these values otherwise the gazebo camera image
        won't be aligned properly with the frame it is supposedly originating from -->
    <origin xyz="${camera_link} 0 0" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_link_optical"/>
  </joint>

  <link name="camera_link_optical">
  </link>
</robot>
